config/routes.rb
require 'sidekiq/web'
require 'api_constraints'

Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
    devise_for :users, path: 'users', controllers: {sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
    
    devise_for :admins, path: 'admins', controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations'}

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'about' => 'about#index'

  get '/user/new' => 'user#new'
  get '/user/login' => 'user#login'
  get '/user/tweet' => 'user#tweet_screen'
  post '/user/tweet' => 'user#tweet'
  
  resources :departments
  get '/department/search' => 'departments#search'
  
  post '/upload/image/any' => 'user#upload_any_image'

  resources :sections

  resources :teachers

  resources :subjects

  resources :students

  resources :exams

  resources :assignments

  resources :users

  resources :admins

  %w( 404 422 500 ).each do |code|
    get code, controller: 'application', action: 'error', code: code
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :departments
      post '/admin' => 'admin#create'
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
      
    end
  end

end

app/models/section.rb
# frozen_string_literal: true

require_relative 'call_backs'
class Section < ApplicationRecord
  self.inheritance_column = :_type_disabled
  belongs_to :department, autosave: true, class_name: 'Department', counter_cache: true, dependent: :destroy, touch: :departments_updated_at, validate: true, required: true
  has_and_belongs_to_many :teachers, association_foreign_key: :teacher_id, class_name: 'Teacher', foreign_key: :section_id, join_table: :sections_teachers, validate: true
  has_and_belongs_to_many :teachers # ,-> { where("experience>=?",0) }, -> { readonly }
  has_one :co_ordinator, class_name: 'Teacher', foreign_key: :id, autosave: false, validate: true
  has_many :subjects, through: :department
  has_many :students
  has_many :good_students, -> { where('percentage>80') }, class_name: 'Student'
  has_many :exams

  validates :department_id, :name, presence: true
  validates :name, format: { with: /[A-Z][A-Z]-2K\d\d/, message: 'Wrong section name pattern' }, length: { is: 7, wrong_length: 'Wrong length of section id, correct: 7' }

  after_destroy CallBacks
  around_save CallBacks
  around_update CallBacks
  around_create CallBacks
end

app/controllers/sections_controller.rb
# frozen_string_literal: true

class SectionsController < ApplicationController

  before_action :authenticate_user!, only: [:show]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
  end

  def show
    id = params[:id].to_i
    @section = Section.find(id)
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(get_params)
    redirect_to section_path(@section) if @section.save
    render :new if @sections.errors.any?
  end

  def edit
  end

  def update; end

  def destroy; end

  private
  def get_params
    params.require(:section).permit(:id, :department_id, :teacher_id)
  end
end

app/views/sections/index.html.erb
    <%= render "/header"%>
    <h1>Sections</h1>
    <%if $isadmin%>
      <%= link_to 'New Section', new_section_path%>
    <%end%>
    <table>
      <th>Dep ID</th>
      <th>Department Name</th>
      <th>Section ID</th>
      <th>Section Name</th>
      <th>CO-ORDINATOR Name</th>
      <th>CO-ORDINATOR ID</th>
      <%if $isadmin%>
        <th></th>
        <th></th>
      <%end%>
      <% Department.all.order(:id).each do |d|%>
        <%d.sections.order(:id).each do |s|%>
          <tr>
            <td><%=d.id-%></td>
            <td><%=d.name-%></td>
            <td><%=s.id%></td>
            <td><%=s.name%></td>
            <td><%=s.co_ordinator.name-%></td>
            <td><%=s.co_ordinator_id-%></td>
            <td><%= link_to 'Show', s%></td>
            <%if $isadmin%>
              <td><%=link_to 'Edit' ,edit_section_path(s)%></td>
              <td><%=link_to 'Delete', s, method: :destroy, data: {confirm: "Are you sure you want to delete #{s.class} #{s.name}?"}%></td>
            <%end%>
          <%end%>
        </tr>
      <%end%>

    </table>
    <%= render "/footer"%>

app/views/sections/select.html.erb
    <%Section.all.each.offset(5) do |t|%>
      <pre><%=t.id%>    <%=t.name%></pre><br/>
    <%end%>

app/views/sections/show.html.erb
    <%= render "/header" -%>

    <% id=request.path[10..-1].to_i%>
      <%section= Section.find(id)%>
        <%if section!=nil%>

          <h1><%=section.name%></h1>
          <h4>ID:
            <%=section.id%></h4>
          <h4>CO-ORDINATOR:
            <%=section.co_ordinator.name%></h4>
          <h4>CO-ORDINATOR ID:
            <%=section.co_ordinator_id%></h4>
          <h4>SUBJECTS:
            <%section.subjects.each do |se|%>
              <a href="/subjects/<%=se.id%>"><%=se.name%></a>
              <%=" "%>
            <%end%>
          </h4>
        <%end%>

        <%= render "/footer"%>